In [8]:
import pandas as pd

i download this dataset on opensourse website.

This data set is all about Real or Fake News or Text dataset.
Here are only 4 columns.
number:
title:
text:
label:
This is all about this dataset.

URL: https://www.kaggle.com/datasets/jillanisofttech/fake-or-real-news

In [10]:
df_dataset_1 = pd.read_csv(r'C:\Users\Kathe\Documents\source_code\ejercicios-en-adalab\Proyecto Personal\DATASET 1\DATASET1 fake_or_real_news.csv')

pd.set_option('display.max_columns', None)

df_dataset_1

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [13]:
print(f'There are {df_dataset_1.shape[0]} rows in Dataset1')
print(f'There are {df_dataset_1.shape[1]} columns in Dataset1')

There are 6335 rows in Dataset1
There are 4 columns in Dataset1

In [15]:
df_dataset_1.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,6335.0,5280.415627,3038.503953,2.0,2674.5,5271.0,7901.0,10557.0

In [16]:
df_dataset_1.describe(include = 'object').T

      count unique                                                top  freq
title  6335   6256                      OnPolitics | 's politics blog     5
text   6335   6060  Killing Obama administration rules, dismantlin...    58
label  6335      2                                               REAL  3171

In [20]:
df_dataset_1['title'].unique()

array(['You Can Smell Hillary’s Fear',
       'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)',
       'Kerry to go to Paris in gesture of sympathy', ...,
       'Anti-Trump Protesters Are Tools of the Oligarchy     : Information',
       'In Ethiopia, Obama seeks progress on peace, security in East Africa',
       "Jeb Bush Is Suddenly Attacking Trump. Here's Why That Matters"],
      shape=(6256,), dtype=object)

In [17]:
df_dataset_1.dtypes

Unnamed: 0     int64
title         object
text          object
label         object
dtype: object

In [18]:
df_dataset_1['label'].value_counts()

label
REAL    3171
FAKE    3164
Name: count, dtype: int64

In [21]:
df_dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6335 non-null   int64
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB

In [26]:
duplicates_df_1 = df_dataset_1[df_dataset_1.duplicated(subset= ['title', 'text'])]


duplicates_df_1

,Unnamed: 0,title,text,label
1492,2697,"University of Missouri, please immediately fir...",To watch the video of photographer Tim Tai get...,REAL
1954,4544,Loretta Lynch becomes first African-American w...,Washington (CNN) Loretta Lynch was sworn in as...,REAL
2336,4396,Obamacare Enrollees Anxiously Await Supreme Co...,"“I’ve got my six-month, regular cancer checkup...",REAL
2856,2664,Donald Trump is blatantly racist — and the med...,"Donald Trump, the actual Republican candidate ...",REAL
2952,7550,"Black Agenda Report for Week of Oct 31, 2016","News, information and analysis from the black ...",FAKE
3081,4160,The College Loan Bombshell Hidden in the Budget,In obscure data tables buried deep in its 2016...,REAL
3292,3056,This astonishing chart shows how moderate Repu...,Political scientists have known for years that...,REAL
3301,1762,OnPolitics | 's politics blog,Who has Trump appointed to his cabinet so far?...,REAL
3324,2399,Senate GOP prepared to replace Obamacare subsi...,"Killing Obama administration rules, dismantlin...",REAL
4140,2261,We Republicans Lost On Gay Rights. That’s A Go...,I’m not among those Republicans who have “evol...,REAL
4405,6824,Paintings 'almost no one else seemed to be doing',"Print \nWhen Judith Gait met “Father X,” it wa...",FAKE
4885,9751,An Open Letter to Black South African Police O...,Tweet Widget by Black Power Front \nWith stude...,FAKE
4971,2906,US faces calls to ‘walk away’ from Iran talks,A leading Republican critic of the Iranian nuc...,REAL
5083,10399,Fighting Ghost Fascists While Aiding Real Ones,2016 presidential campaign by BAR executive ed...,FAKE
5105,4171,Clinton clinches Democratic nomination – Sande...,Hillary Clinton clinched the Democratic presid...,REAL
5127,2271,OnPolitics | 's politics blog,Who has Trump appointed to his cabinet so far?...,REAL
5414,374,"Do Democrats Want What Bernie Wants, Or Just W...","Do Democrats Want What Bernie Wants, Or Just W...",REAL
5417,9792,"Black Agenda Radio for Week of Nov. 7, 2016","News, information and analysis from the black ...",FAKE
5478,6088,"FEAR OF TRUMP: BUSH, OBAMA, CLINTON ALL BUYING...",Email \n\nIt appears Bill and Hillary Clinton ...,FAKE
5500,10311,Saudi ambassador to the UAE: Any contact with ...,Email \n\nAccording to a report by an Emirati ...,FAKE
5536,3157,Anti-Trump forces seek last-ditch delegate revolt,Washington (CNN) The faction of the GOP that i...,REAL
5627,1844,Clinton clearing primary field for potential 2...,Hillary Clinton appears to have scared away mu...,REAL
5705,3025,Political polarization is getting worse. Every...,You've probably seen this chart.\n\nIt uses an...,REAL
5916,10075,Is it possible that Saudi King be tried in US ...,Email \n\nAccording to the JASTA law which all...,FAKE
5966,2236,There’s a good reason protesters at the Univer...,Video of a confrontation between a news photog...,REAL
6083,8503,Biden Blames “Lazy American Women” For The Eco...,Email \n\nDemocratic Vice President Joe Biden ...,FAKE
6148,9725,Hillary’s “Big Tent” is Obama’s “Grand Bargain...,2016 presidential campaign by BAR executive ed...,FAKE
6227,8613,ISIS uses an industrial dough kneader to kill ...,Email \nISIS barbarians used an industrial dou...,FAKE
6233,7171,North Korea Threatens ‘Sacred’ Nuclear War Aga...,Email \nNorth Korea’s Foreign Ministry slammed...,FAKE

In [ ]:
#should i do this?


#df = df_dataset_1.drop_duplicates(subset=['title', 'text'])

In [27]:
df_dataset_1 = df_dataset_1.drop('Unnamed: 0', axis=1)

df_dataset_1.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL