In [1]:
import pandas as pd

In [2]:
#1. Crea una serie con números correlativos entre 1 y 12 inclusive (puedes hacerlo como lista o diccionario):

lista_q1 = list(range(1,13))

print(lista_q1)

serie_q1 = pd.Series(lista_q1)

print(serie_q1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [3]:
# Cambia el indice de la serie anteriormente creada para que comience con el numero 20.

serie_q1 = pd.Series(lista_q1, index = range(20, 20 + len(lista_q1)))

print(serie_q1)

20     1
21     2
22     3
23     4
24     5
25     6
26     7
27     8
28     9
29    10
30    11
31    12
dtype: int64

In [4]:
#Nuevamente cambia el indice de la serie, esta vez con una lista que haga referencia a los meses del año 
#(tenemos 12 elementos como la cantidad de meses del año).

meses_lista = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

serie_q1_meses = pd.Series(lista_q1, index=meses_lista)

print(serie_q1_meses)

Jan     1
Feb     2
Mar     3
Apr     4
May     5
Jun     6
Jul     7
Aug     8
Sep     9
Oct    10
Nov    11
Dec    12
dtype: int64

In [5]:
#Muestra los valores que están en la posición 3 y 8 de mi serie.
serie_q1_meses[[3, 8]]

C:\Users\Kathe\AppData\Local\Temp\ipykernel_21140\918166896.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie_q1_meses[[3, 8]]

Apr    4
Sep    9
dtype: int64

In [6]:
#Muestra los valores que están etiquetados en enero y agosto.

serie_q1_meses[['Jan', 'Aug']]

Jan    1
Aug    8
dtype: int64

In [7]:
#Muestra sus valores, indices, forma, tamaño y el tipo de elementos de la serie

print(serie_q1_meses.values)
print(serie_q1_meses.index)
print(serie_q1_meses.shape)
print(serie_q1_meses.size)
print(serie_q1_meses.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
       'Nov', 'Dec'],
      dtype='object')
(12,)
12
int64

In [10]:
#2. Abre el fichero de rating-and-performance con el método que sea más correcto. 
# Además muestra las 5 primeras filas del DataFrame.

df_q2 = pd.read_csv("ratingandperformance.csv")

In [12]:
df_q2.head()

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [14]:
#Cread una nueva columna donde tengamos la diferencia entre el precio al que vende el e-commerce menos el precio del minorista. 
#Insertad esta columna en la posición dos.

# Calculate the difference between 'retail_price' and 'price'
df_q2["price_diff"] = df_q2["retail_price"] - df_q2["price"]

# Insert the new column at position 2
df_q2.insert(2, "price_diff", df_q2.pop("price_diff"))

In [17]:
df_q2.insert(0, 'diferencia_precios', (df_q2['price'] - df_q2['retail_price']))

In [18]:
df_q2

,diferencia_precios,index,title,price_diff,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2.00,0,2020 Summer Vintage Flamingo Print Pajamas Se...,-2.00,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,-14.00,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,14.00,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,-35.00,2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,35.00,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,0.00,3,Hot Summer Cool T-shirt pour les femmes Mode T...,0.00,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,-0.28,4,Femmes Shorts d'été à lacets taille élastique ...,0.28,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,-3.00,1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,3.00,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,-54.00,1569,10 couleurs femmes shorts d'été lacent ceintur...,54.00,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,-14.00,1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,14.00,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,2.00,1571,Mode femmes d'été sans manches robes col en V ...,-2.00,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,1.00,1572,Pantalon de yoga pour femmes à la mode Slim Fi...,-1.00,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [20]:
#Extraed todas las filas de la columna "price". ¿De qué tipo es el resultado obtenido?

df_q2.loc[:,'price']

0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

In [21]:
#Extraed todas las filas de las columnas "price" y "retail_price". ¿De qué tipo es el resultado obtenido?

df_q2.loc[:,['price', 'retail_price']]

      price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]

In [23]:
#Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".


df_q2.loc[::2,["rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count"]]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0

In [27]:
#Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 5000.

df_2_cond = df_q2.loc[(df_q2['price'] > 10) & (df_q2['units_sold'] > 5000)]

df_2_cond.head()

,diferencia_precios,index,title,price_diff,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
16,1.0,16,Nouvelle mode d'été pour femmes Robe sans manc...,-1.0,New Summer Women's Fashion Sleeveless Polka Do...,11.0,10,EUR,10000,0,...,6302,3.958426,5b8beef49996c87b299cdbec,0,NaN,https://www.wish.com/c/5cd3e795ebe403118bbc0f89,https://contestimg.wish.com/api/webimage/5cd3e...,5cd3e795ebe403118bbc0f89,summer,2020-08
77,1.0,77,Nouveau Mode Femmes Casual Shorts Costume Été ...,-1.0,New Fashion Women Casual Shorts Suit Summer Ti...,11.0,10,EUR,10000,0,...,9200,4.289674,583e7f658108913bced6f8cf,0,NaN,https://www.wish.com/c/5b29e5b5080ea2661b2287f6,https://contestimg.wish.com/api/webimage/5b29e...,5b29e5b5080ea2661b2287f6,summer,2020-08
89,1.0,89,NOUVELLE Robe d'été sans manches imprimée à fl...,-1.0,NEW Women Summer Floral Printed Sleeveless Dr...,11.0,10,EUR,20000,1,...,12974,3.965701,5a7b23a69bda4e3d375e7b3f,0,NaN,https://www.wish.com/c/5cf5e44b3c8b9e101a5db52c,https://contestimg.wish.com/api/webimage/5cf5e...,5cf5e44b3c8b9e101a5db52c,summer,2020-08
109,1.0,109,Casual femmes ras du cou à manches courtes feu...,-1.0,Casual Women Crew Neck Short Sleeve Leaf Print...,11.0,10,EUR,10000,0,...,13946,4.000143,559d33adc605853731afbf10,0,NaN,https://www.wish.com/c/5c78151c27202a28a75752b7,https://contestimg.wish.com/api/webimage/5c781...,5c78151c27202a28a75752b7,summer,2020-08
111,2.0,111,Femmes classiques dos nu en dentelle évider li...,-2.0,Classic Women Backless Lace Hollow Out Halter ...,14.0,12,EUR,10000,0,...,32858,3.885538,57baf75f63834218e305e4f4,0,NaN,https://www.wish.com/c/5acb7ae3a69e662bb0133546,https://contestimg.wish.com/api/webimage/5acb7...,5acb7ae3a69e662bb0133546,summer,2020-08

In [29]:
df_q2.head()

,diferencia_precios,index,title,price_diff,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2.00,0,2020 Summer Vintage Flamingo Print Pajamas Se...,-2.00,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,-14.00,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,14.00,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,-35.00,2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,35.00,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,0.00,3,Hot Summer Cool T-shirt pour les femmes Mode T...,0.00,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,-0.28,4,Femmes Shorts d'été à lacets taille élastique ...,0.28,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [30]:
#Extraed todas las filas de la columna "price" CON ILOC

df_q2.iloc[ : , 5]

0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

In [31]:
#Extraed todas las filas de las columnas "price" y "retail_price".

df_q2.iloc[ : , [5,6]]

      price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]

In [36]:
print(df_q2.columns)

Index(['diferencia_precios', 'index', 'title', 'price_diff', 'title_orig',
       'price', 'retail_price', 'currency_buyer', 'units_sold',
       'uses_ad_boosts', 'rating', 'rating_count', 'rating_five_count',
       'rating_four_count', 'rating_three_count', 'rating_two_count',
       'rating_one_count', 'badges_count', 'badge_local_product',
       'badge_product_quality', 'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'product_variation_inventory',
       'shipping_option_name', 'shipping_option_price', 'shipping_is_express',
       'countries_shipped_to', 'inventory_total', 'has_urgency_banner',
       'urgency_text', 'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

In [40]:
#Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

column_list = ["rating", "rating_count", "rating_five_count", "rating_four_count", 
               "rating_three_count", "rating_two_count", "rating_one_count"]

indexes = [df_q2.columns.get_loc(col) for col in column_list]



df_q2.iloc[:, indexes]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,3.76,54,26.0,8.0,10.0,1.0,9.0
1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
3,4.03,579,295.0,119.0,87.0,42.0,36.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
...,...,...,...,...,...,...,...
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1569,3.07,28,11.0,3.0,1.0,3.0,10.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1571,2.50,2,0.0,1.0,0.0,0.0,1.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0